#! /bin/bash

pdflatex COO_HallB-CLAS12_rgF.tex
pdflatex COO_HallB-CLAS12_rgF.tex

rm -f *.tex~ *.mtc1 *.aux *.dvi *.lof *.log *.out *.lot *.toc *.brf *.maf 
rm -f *.mtc *.mtc0 *.nlo *.bbl *.blg
rm -rf *.t2d *.fls *.fdb_latexmk 

